language: c
dist: trusty

git:
  depth: 5

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install -y gcc-multilib libudev-dev libusb-1.0-0-dev;
    fi
  - "$CC --version"

script:
  - make
